[package]

name = "solicit"
version = "0.0.1"
authors = ["Marko Lalic <marko.lalic@gmail.com>"]

[dependencies]
log = "^0.3"

[dependencies.hpack]
git = "https://github.com/mlalic/hpack-rs.git"

[dependencies.openssl]
version = "*"
features = ["tlsv1_2", "npn"]
